spring.application.name=CrazyBet
spring.datasource.url=jdbc:mysql://localhost:3306/CrazyBet?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=zR4uW7pX9vK2mN5bQ8eT1yU4iO7pA0sD3fG6hJ9kL2mN5bQ8eT1yU4iO7pA0sD3f
